version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "00:52"  # This is 9:00 AM Turkey Time (UTC+3)
      timezone: "Europe/Istanbul"  # Explicitly setting Turkey timezone
    labels:
      - "dependencies"
      - "github-actions"
      - "automated-pr"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5
    assignees:
      - "dependabot"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "00:52"  # This is 9:00 AM Turkey Time (UTC+3)
      timezone: "Europe/Istanbul"  # Explicitly setting Turkey timezone
    labels:
      - "dependencies"
      - "ruby"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5
    assignees:
      - "dependabot"
