version: 2
updates:
  # Daily updates (non-security)
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:45"
      timezone: "Europe/Berlin"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "firebase-ios-sdk"
      - dependency-name: "facebook-ios-sdk"
      - dependency-name: "fullstory-swift-package-ios"
      - dependency-name: "Instabug-SP"
    groups:
      ios-dependencies:
        patterns: ["*"]
        exclude-patterns:
          - "firebase-*"
          - "facebook-*"
          - "fullstory-*"
          - "Instabug-SP"
        applies-to: "version-updates"
    open-pull-requests-limit: 200
    rebase-strategy: "auto"
    insecure-external-code-execution: "deny"
    labels: ["dependencies", "swift"]
    assignees: ["@shadyghalab"]
    reviewers: ["@mobile-team"]
    milestone: 1
    commit-message:
      prefix: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    target-branch: "develop"