version: 2
updates:
  # GitHub Actions Dependencies
  - package-ecosystem: "github-actions"
    directory: "/" # Root directory for GitHub Actions
    schedule:
      interval: "daily"
      time: "14:58" # 09:00 Istanbul time (UTC+3)
    labels:
      - "dependency-update"
      - "github-actions"
    commit-message:
      prefix: "chore(deps):"
    open-pull-requests-limit: 5

  # Bundler (Ruby Gems) Dependencies
  - package-ecosystem: "bundler"
    directory: "/" # Root directory for Gemfile
    schedule:
      interval: "daily"
      time: "14:58" # 09:00 Istanbul time (UTC+3)
    labels:
      - "dependency-update"
      - "ruby-gems"
    commit-message:
      prefix: "chore(deps):"
    open-pull-requests-limit: 5
