version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:10"  # 4:00 PM in Taiwan / 10:00 AM in Central Europe
      timezone: "UTC"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "firebase-ios-sdk"
      - dependency-name: "facebook-ios-sdk"
      - dependency-name: "fullstory-swift-package-ios"
      - dependency-name: "Instabug-SP"
    groups:
      ios-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "firebase-*"
          - "facebook-*"
          - "fullstory-*"
          - "Instabug-SP"
        applies-to: "version-updates"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    security-updates-only: false
    insecure-external-code-execution: "deny"
    labels:
      - "dependencies"
      - "swift"
    assignees:
      - "@shady.mostafa"
    reviewers:
      - "@mobile-team"
    milestone: 1
    commit-message:
      prefix: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    target-branch: "develop"

  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "monthly"
    security-updates-only: true
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "firebase-ios-sdk"
      - dependency-name: "facebook-ios-sdk"
      - dependency-name: "fullstory-swift-package-ios"
      - dependency-name: "Instabug-SP"
