on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  dependabot-labeler:
    runs-on: [self-hosted, iOS]
    strategy:
      matrix:
        dependency-type: 
          - 'direct:production'
          - 'direct:development'
          - 'direct:security'
          - 'direct:patch'
          - 'direct:major'
          - 'direct:minor'
          - 'direct:experimental'
          - 'direct:deprecated'
          - 'direct:external'
          - 'direct:internal'
          - 'direct:automated'
          - 'direct:doc'
          - 'direct:performance'
          - 'direct:staging'
          - 'direct:ci'
        include:
          - dependency-type: 'direct:production'
            label: 'dependencies:production'
          # ... (rest unchanged)
    
    steps:
      - name: Fetch metadata for Dependabot PR
        id: metadata
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-label PR based on dependency type
        run: |
          echo "Dependency type: ${{ steps.metadata.outputs.dependency-type }}"
          if [[ "${{ steps.metadata.outputs.dependency-type }}" == "${{ matrix.dependency-type }}" ]]; then
            gh pr edit "$PR_URL" --add-label "${{ matrix.label }}"
          fi
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
