name: Auto-label Dependabot PRs with metadata-based labels

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  label-dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch metadata
        id: metadata
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add label based on dependency type
        run: |
          TYPE="${{ steps.metadata.outputs.dependency-type }}"
          echo "Dependency type is: $TYPE"

          declare -A label_map=(
            ["direct:production"]="dependencies:production"
            ["direct:development"]="dependencies:development"
            ["direct:security"]="dependencies:security"
            ["direct:patch"]="dependencies:patch"
            ["direct:major"]="dependencies:major"
            ["direct:minor"]="dependencies:minor"
            ["direct:experimental"]="dependencies:experimental"
            ["direct:deprecated"]="dependencies:deprecated"
            ["direct:external"]="dependencies:external"
            ["direct:internal"]="dependencies:internal"
            ["direct:automated"]="dependencies:automated"
            ["direct:doc"]="dependencies:doc"
            ["direct:performance"]="dependencies:performance"
            ["direct:staging"]="dependencies:staging"
            ["direct:ci"]="dependencies:ci"
          )

          LABEL="${label_map[$TYPE]}"
          if [ -n "$LABEL" ]; then
            echo "Applying label: $LABEL"
            gh pr edit "$PR_URL" --add-label "$LABEL"
          else
            echo "No label mapped for: $TYPE"
          fi
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
