name: Auto-label Dependabot PRs with metadata-based labels
description: Automatically adds labels to Dependabot PRs based on metadata information, such as production dependencies, security updates, and more.

on: pull_request

permissions:
  pull-requests: write
  issues: write

jobs:
  dependabot-labeler:
    runs-on: [self-hosted, iOS]
    if: github.event.pull_request.user.login == 'dependabot[bot]' && startsWith(github.repository, 'DependabotTest')
    strategy:
      matrix:
        dependency-type: 
          - 'direct:production'
          - 'direct:development'
          - 'direct:security'
          - 'direct:patch'
          - 'direct:major'
          - 'direct:minor'
          - 'direct:experimental'
          - 'direct:deprecated'
          - 'direct:external'
          - 'direct:internal'
          - 'direct:automated'
          - 'direct:doc'
          - 'direct:performance'
          - 'direct:staging'
          - 'direct:ci'
        include:
          - dependency-type: 'direct:production'
            label: 'dependencies:production'
          - dependency-type: 'direct:development'
            label: 'dependencies:development'
          - dependency-type: 'direct:security'
            label: 'dependencies:security'
          - dependency-type: 'direct:patch'
            label: 'dependencies:patch'
          - dependency-type: 'direct:major'
            label: 'dependencies:major'
          - dependency-type: 'direct:minor'
            label: 'dependencies:minor'
          - dependency-type: 'direct:experimental'
            label: 'dependencies:experimental'
          - dependency-type: 'direct:deprecated'
            label: 'dependencies:deprecated'
          - dependency-type: 'direct:external'
            label: 'dependencies:external'
          - dependency-type: 'direct:internal'
            label: 'dependencies:internal'
          - dependency-type: 'direct:automated'
            label: 'dependencies:automated'
          - dependency-type: 'direct:doc'
            label: 'dependencies:doc'
          - dependency-type: 'direct:performance'
            label: 'dependencies:performance'
          - dependency-type: 'direct:staging'
            label: 'dependencies:staging'
          - dependency-type: 'direct:ci'
            label: 'dependencies:ci'

    steps:
      - name: Fetch metadata for Dependabot PR
        id: metadata
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-label PR based on dependency type
        if: steps.metadata.outputs.dependency-type == ${{ matrix.dependency-type }}
        run: gh pr edit "$PR_URL" --add-label "${{ matrix.label }}"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}